import {escapeHTML as h,validateQuiz,validateCatalog,filterQuizzes,grade,newAttempt,restoreAttempt,storageKey} from './core.mjs';
const root=document.querySelector('#main');
const difficulty={easy:'Einstieg',medium:'Fortgeschritten',hard:'Experte'};
let catalog,quiz,attempt,loading=0;
const filters={search:'',faction:'',detachment:'',difficulty:''};
const readStore=key=>{try{return localStorage.getItem(key);}catch{return null;}};
function writeStore(key,value){try{localStorage.setItem(key,value);}catch{document.querySelector('#storage-notice').textContent='Speichern ist in diesem Browser nicht verfügbar; das Quiz funktioniert für diese Sitzung.';}}
function save(){if(quiz&&attempt)writeStore(storageKey(quiz),JSON.stringify(attempt));}
function applyTheme(value){document.documentElement.dataset.theme=value;document.querySelector('#theme').setAttribute('aria-label',value==='dark'?'Helle Darstellung aktivieren':'Dunkle Darstellung aktivieren');}
applyTheme(readStore('pkstratagems:quiz:theme')==='light'?'light':'dark');
document.querySelector('#theme').addEventListener('click',()=>{const v=document.documentElement.dataset.theme==='dark'?'light':'dark';applyTheme(v);writeStore('pkstratagems:quiz:theme',v);});
const options=(values,empty,selected)=>`<option value="">${empty}</option>`+[...new Set(values)].sort().map(v=>`<option value="${h(v)}" ${selected===v?'selected':''}>${h(v)}</option>`).join('');
function changePage(id=''){const u=new URL(location.href);u.search='';if(id)u.searchParams.set('quiz',id);history.pushState({},'',u);route();}
function heading(q){return `<a class="back" href="./" data-catalog>← Alle Quizze</a><div class="quiz-head"><p class="eyebrow">Fraktionstraining / ${h(q.detachment)}</p><h1>${h(q.title)}</h1><span class="chip">${h(q.faction)}</span><span class="chip">${h(q.detachment)}</span><span class="chip">${difficulty[q.difficulty]}</span><span class="chip">${q.questionCount} Fragen</span><p class="small">${h(q.rulesBasis)}</p></div>`;}
function sourceHTML(ids){return `<details class="sources"><summary>Quellen und Regelstand</summary>${ids.map(id=>quiz.sources.find(s=>s.id===id)).filter(Boolean).map(s=>`<p><strong>${h(s.title)}</strong><br>${h(s.locator)}${s.url&&/^https:\/\//.test(s.url)?` · <a href="${h(s.url)}" target="_blank" rel="noopener noreferrer">Quelle öffnen</a>`:''}</p>`).join('')}<p>${h(quiz.sourceNote)}</p></details>`;}
function renderCatalog(){quiz=null;attempt=null;root.innerHTML=`<section class="hero"><p class="eyebrow">PK Stratagems / Trainingsarchiv</p><h1>Regeln kennen.<br>Richtig entscheiden.</h1><p class="lead">Quizze zu Fraktionen, Detachments und Stratagems. Erst selbst entscheiden, dann mit Erklärung und Quelle nachlesen.</p><div class="hero-stats"><span class="chip">${catalog.quizzes.length} ${catalog.quizzes.length===1?'Quiz verfügbar':'Quizze verfügbar'}</span><span class="chip">Eine Antwort je Frage</span><span class="chip">Ohne Zeitdruck</span></div></section><form class="filter-box" id="filters" role="search"><label>Suchen<input type="search" id="quiz-search" placeholder="Fraktion, Detachment oder Thema …" value="${h(filters.search)}"></label><label>Fraktion<select id="faction-filter">${options(catalog.quizzes.map(q=>q.faction),'Alle Fraktionen',filters.faction)}</select></label><label>Detachment<select id="detachment-filter">${options(catalog.quizzes.filter(q=>!filters.faction||q.faction===filters.faction).map(q=>q.detachment),'Alle Detachments',filters.detachment)}</select></label><label>Schwierigkeit<select id="difficulty-filter"><option value="">Alle Stufen</option>${Object.entries(difficulty).map(([id,label])=>`<option value="${id}" ${filters.difficulty===id?'selected':''}>${label}</option>`).join('')}</select></label></form><p id="catalog-count" class="small catalog-count" role="status"></p><section class="catalog-grid" id="catalog" aria-label="Verfügbare Quizze"></section><p class="notice" style="margin-top:28px">Wähle ein Quiz nach Fraktion und Detachment. Weitere Themen können unabhängig ergänzt werden. Die angegebenen Quellenstände sind Lernstände, keine automatische Prüfung späterer Regeländerungen.</p>`;renderCards();}
function renderCards(){const items=filterQuizzes(catalog.quizzes,filters);document.querySelector('#catalog-count').textContent=items.length+' von '+catalog.quizzes.length+' Quizzen';document.querySelector('#catalog').innerHTML=items.length?items.map(q=>`<article class="quiz-card"><span class="eyebrow">${h(q.faction)}</span><h2>${h(q.title)}</h2><p>${h(q.description)}</p><p class="small">${q.questionCount} Fragen · ${difficulty[q.difficulty]} · ca. ${q.estimatedMinutes||8} Minuten</p><div class="tags">${q.tags.map(t=>`<span class="chip">${h(t)}</span>`).join('')}</div><a class="button primary" href="?quiz=${encodeURIComponent(q.id)}" data-open="${q.id}">Quiz öffnen →</a></article>`).join(''):`<div class="empty"><h2>Kein passendes Quiz</h2><p>Für diese Auswahl ist noch kein Quiz hinterlegt.</p><button data-clear-filters>Filter zurücksetzen</button></div>`;}
function intro(){const g=attempt?grade(quiz,attempt.answers,attempt.questionIds):null;root.innerHTML=`<div class="quiz-workspace">${heading(quiz)}<section class="question-card"><h2>Bereit für den Regelcheck?</h2><p>${h(quiz.intro)}</p><p><strong>${quiz.questionCount} Fragen · ${quiz.questionCount} mögliche Punkte.</strong><br>Je Frage ist genau eine Antwort richtig. Die Lösungen werden erst nach der Auswertung angezeigt.</p>${g?.answered?`<p class="notice">Gespeicherter Versuch: ${g.answered}/${g.total} beantwortet${attempt.submitted?' · bereits ausgewertet':''}. Die Speicherung gilt nur für diesen Browser.</p>`:''}<div class="button-row">${g?.answered?'<button data-reset>Neu beginnen</button>':''}<button class="primary" data-start>${g?.answered?(attempt.submitted?'Ergebnis ansehen':'Versuch fortsetzen'):'Quiz starten'}</button></div>${sourceHTML(quiz.sources.map(s=>s.id))}</section></div>`;}
function focusContent(selector){requestAnimationFrame(()=>{const el=root.querySelector(selector);el?.focus({preventScroll:true});el?.scrollIntoView({behavior:'instant',block:'start'});});}
function renderQuestion(focus=false,message=''){const g=grade(quiz,attempt.answers,attempt.questionIds),id=attempt.questionIds[attempt.position],q=quiz.questions.find(q=>q.id===id);root.innerHTML=`<div class="quiz-workspace">${heading(quiz)}<div class="progress-top"><span id="progress-label" role="status">${g.answered} von ${g.total} beantwortet</span><span>${g.total<quiz.questionCount?'Fehlertraining':'Regelcheck'}</span></div><div class="progress-track" aria-hidden="true"><div class="progress-fill" style="width:${100*g.answered/g.total}%"></div></div><nav class="question-nav" aria-label="Fragen auswählen">${attempt.questionIds.map((id,i)=>`<button type="button" data-position="${i}" ${attempt.position===i?'aria-current="step"':''} class="${attempt.answers[id]?'answered':''}" aria-label="Frage ${i+1}${attempt.answers[id]?', beantwortet':''}">${i+1}</button>`).join('')}</nav>${message?`<div role="alert" class="alert">${h(message)}</div>`:''}<section class="question-card"><p class="eyebrow">Frage ${attempt.position+1} / ${g.total} · ${h(q.topic||'Regelwissen')}</p><fieldset><legend tabindex="-1" id="question-title">${h(q.prompt)}</legend>${q.options.map((o,i)=>`<label class="answer-option"><input type="radio" name="answer" value="${h(o.id)}" ${attempt.answers[q.id]===o.id?'checked':''}><span><span class="option-letter">${String.fromCharCode(65+i)}</span>${h(o.text)}</span></label>`).join('')}</fieldset><div class="button-row"><button class="left" data-prev ${attempt.position===0?'disabled':''}>← Zurück</button>${attempt.position<g.total-1?'<button class="primary" data-next>Weiter →</button>':'<button class="primary" data-submit>Quiz auswerten</button>'}</div></section><p class="small quiz-help">Du kannst Antworten bis zur Auswertung ändern. Fortschritt wird lokal gespeichert. Es werden keine Spielerprofile angelegt.</p><div class="button-row"><button data-reset>Versuch zurücksetzen</button>${attempt.position<g.total-1?'<button data-submit>Auswerten</button>':''}</div></div>`;if(focus)focusContent('#question-title');}
function renderResult(focus=false){const g=grade(quiz,attempt.answers,attempt.questionIds);root.innerHTML=`<div class="quiz-workspace">${heading(quiz)}<section class="result-hero" aria-label="Quiz-Ergebnis"><div class="score-number">${g.correct}<span class="small"> / ${g.total}</span></div><div><h2 id="result-title" tabindex="-1">${g.correct===g.total?'Alles richtig.':g.percent>=50?'Gute Grundlage.':'Die Details machen den Unterschied.'}</h2><p style="margin-bottom:0">${g.percent} % richtig${g.total<quiz.questionCount?' · Fehlertraining':''}. ${g.correct===g.total?'Prüfe auch die Begründungen.':'Lies die Erklärungen und wiederhole die offenen Punkte.'}</p></div></section><div class="button-row" style="margin:0 0 30px"><button data-reset>Gesamtes Quiz wiederholen</button>${g.wrongIds.length?'<button class="primary" data-retry-wrong>Nur Fehler wiederholen</button>':''}<button data-share>Quizlink kopieren</button></div><p id="share-status" class="small" role="status"></p><div class="result-list">${g.rows.map((row,i)=>{const q=quiz.questions.find(q=>q.id===row.id);return `<article class="review-card"><div class="review-state ${row.correct?'':'wrong'}">${row.correct?'✓ Richtig':'✕ Nicht richtig'} · Frage ${i+1}</div><h3>${h(q.prompt)}</h3>${q.options.map((o,i)=>{const correct=o.id===q.correctOptionId,chosen=o.id===row.selected;return `<div class="review-option ${correct?'correct':chosen?'wrong':''}"><span class="option-letter">${String.fromCharCode(65+i)}</span>${h(o.text)}${correct?`<span class="answer-badge">✓ Richtige Antwort${chosen?' · deine Auswahl':''}</span>`:chosen?'<span class="answer-badge">✕ Deine Auswahl</span>':''}</div>`;}).join('')}<p class="explanation"><strong>Warum?</strong> ${h(q.explanation)}</p>${sourceHTML(q.sourceIds)}</article>`;}).join('')}</div><div class="button-row"><a class="button" href="./" data-catalog>Zur Quizübersicht</a><button data-reset>Neu starten</button></div></div>`;if(focus)focusContent('#result-title');}
async function route(){const ticket=++loading;const id=new URL(location.href).searchParams.get('quiz');if(!id){renderCatalog();return;}const entry=catalog.quizzes.find(q=>q.id===id);if(!entry){root.innerHTML='<section class="empty"><h1>Quiz nicht gefunden</h1><p>Dieser Link gehört zu keinem veröffentlichten Quiz.</p><a class="button" href="./" data-catalog>Zur Quizübersicht</a></section>';return;}root.innerHTML='<p role="status">Quiz wird geladen …</p>';try{const response=await fetch('./data/'+entry.file,{cache:'no-cache'});if(!response.ok)throw new Error('Quizdatei ist gerade nicht erreichbar.');const data=validateQuiz(await response.json());if(ticket!==loading)return;if(data.id!==entry.id)throw new Error('Quizzuordnung stimmt nicht.');quiz=data;attempt=restoreAttempt(quiz,readStore(storageKey(quiz)));intro();}catch(e){if(ticket===loading)root.innerHTML=`<div class="alert" role="alert">${h(e.message)}</div><a class="button" href="./" data-catalog>Zur Quizübersicht</a>`;}}
root.addEventListener('input',e=>{if(e.target.id==='quiz-search'){filters.search=e.target.value;renderCards();}});
root.addEventListener('change',e=>{const map={'faction-filter':'faction','detachment-filter':'detachment','difficulty-filter':'difficulty'};if(map[e.target.id]){filters[map[e.target.id]]=e.target.value;if(e.target.id==='faction-filter'){filters.detachment='';document.querySelector('#detachment-filter').innerHTML=options(catalog.quizzes.filter(q=>!filters.faction||q.faction===filters.faction).map(q=>q.detachment),'Alle Detachments','');}renderCards();}if(e.target.name==='answer'&&attempt&&!attempt.submitted){attempt.answers[attempt.questionIds[attempt.position]]=e.target.value;save();const g=grade(quiz,attempt.answers,attempt.questionIds);root.querySelector('#progress-label').textContent=`${g.answered} von ${g.total} beantwortet`;root.querySelector('.progress-fill').style.width=(100*g.answered/g.total)+'%';const b=root.querySelector(`[data-position="${attempt.position}"]`);b.classList.add('answered');b.setAttribute('aria-label',`Frage ${attempt.position+1}, beantwortet`);}});
root.addEventListener('submit',e=>e.preventDefault());
root.addEventListener('click',async e=>{const b=e.target.closest('button,a');if(!b)return;if(b.hasAttribute('data-catalog')){e.preventDefault();changePage();return;}if(b.dataset.open){e.preventDefault();changePage(b.dataset.open);return;}if(b.hasAttribute('data-clear-filters')){Object.keys(filters).forEach(k=>filters[k]='');renderCatalog();return;}if(!quiz)return;if(b.hasAttribute('data-start')){attempt ||= newAttempt(quiz);attempt.submitted?renderResult(true):renderQuestion(true);return;}if(b.hasAttribute('data-reset')){document.querySelector('#reset-dialog').showModal();return;}if(!attempt)return;if(b.hasAttribute('data-position')){attempt.position=Number(b.dataset.position);save();renderQuestion(true);}if(b.hasAttribute('data-next')||b.hasAttribute('data-prev')){attempt.position+=b.hasAttribute('data-next')?1:-1;attempt.position=Math.max(0,Math.min(attempt.position,attempt.questionIds.length-1));save();renderQuestion(true);}if(b.hasAttribute('data-submit')){const g=grade(quiz,attempt.answers,attempt.questionIds);if(g.answered!==g.total){attempt.position=attempt.questionIds.indexOf(g.rows.find(q=>!q.answered).id);renderQuestion(true,`Noch ${g.total-g.answered} ${g.total-g.answered===1?'Frage offen':'Fragen offen'}. Bitte wähle erst bei jeder Frage eine Antwort.`);}else{attempt.submitted=true;save();renderResult(true);}}if(b.hasAttribute('data-retry-wrong')){const ids=grade(quiz,attempt.answers,attempt.questionIds).wrongIds;attempt=newAttempt(quiz,ids);save();renderQuestion(true);}if(b.hasAttribute('data-share')){const url=new URL(location.href);url.search='';url.searchParams.set('quiz',quiz.id);try{await navigator.clipboard.writeText(url.href);document.querySelector('#share-status').textContent='Quizlink kopiert. Er enthält keine Antworten oder Ergebnisse.';}catch{document.querySelector('#share-status').textContent='Bitte den Link aus der Adresszeile kopieren. Er enthält keine Antworten oder Ergebnisse.';}}});
document.querySelector('#reset-dialog').addEventListener('close',e=>{if(e.target.returnValue==='reset'&&quiz){attempt=newAttempt(quiz);save();renderQuestion(true);}});
window.addEventListener('popstate',()=>{if(catalog)route();});
try{const response=await fetch('./data/index.json',{cache:'no-cache'});if(!response.ok)throw new Error('Der Quizkatalog ist gerade nicht erreichbar.');catalog=validateCatalog(await response.json());await route();}catch(e){root.innerHTML=`<div role="alert" class="alert">${h(e.message)} Bitte die Seite erneut laden.</div>`;}
