import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {validateQuiz,validateCatalog,filterQuizzes,grade,newAttempt,restoreAttempt,storageKey,escapeHTML} from '../quiz/core.mjs';
const q=JSON.parse(fs.readFileSync(new URL('../quiz/data/imperial-agents-imperialis-fleet-grundlagen.json',import.meta.url)));
const catalog=JSON.parse(fs.readFileSync(new URL('../quiz/data/index.json',import.meta.url)));
test('schema and catalog valid',()=>{validateQuiz(q);validateCatalog(catalog);assert.equal(q.questions.length,8)});
for(const question of q.questions)for(const option of question.options)test(`${question.id}: ${option.id}`,()=>{const g=grade(q,{[question.id]:option.id},[question.id]);assert.equal(g.total,1);assert.equal(g.answered,1);assert.equal(g.correct,option.id===question.correctOptionId?1:0);});
test('full score',()=>assert.equal(grade(q,Object.fromEntries(q.questions.map(x=>[x.id,x.correctOptionId]))).correct,8));
test('empty cannot look complete',()=>{const g=grade(q);assert.equal(g.answered,0);assert.equal(g.correct,0);assert.equal(g.wrongIds.length,8)});
test('no answer count for unknown choice',()=>assert.equal(grade(q,{[q.questions[0].id]:'fake'}).answered,0));
test('retry uses subset denominator',()=>{const first=q.questions[0];assert.equal(grade(q,{[first.id]:first.correctOptionId},[first.id]).percent,100)});
test('new attempt separated from previous',()=>{const a=newAttempt(q);const b=newAttempt(q);a.answers[q.questions[0].id]='option-1';assert.deepEqual(b.answers,{})});
test('restore answered state',()=>{const a=newAttempt(q);a.answers[q.questions[0].id]='option-1';a.position=3;assert.deepEqual(restoreAttempt(q,JSON.stringify(a)),a)});
test('malformed storage ignored',()=>assert.equal(restoreAttempt(q,'{broken'),null));
test('other quiz ignored',()=>assert.equal(restoreAttempt(q,JSON.stringify({...newAttempt(q),quizId:'other-quiz'})),null));
test('other version ignored',()=>assert.equal(restoreAttempt(q,JSON.stringify({...newAttempt(q),revision:'old'})),null));
test('forged submitted flag ignored',()=>assert.equal(restoreAttempt(q,JSON.stringify({...newAttempt(q),submitted:true})).submitted,false));
test('unknown question ignored',()=>assert.equal(restoreAttempt(q,JSON.stringify({...newAttempt(q),questionIds:['fake']})),null));
test('source references required',()=>{const x=structuredClone(q);x.questions[0].sourceIds=['fake'];assert.throws(()=>validateQuiz(x))});
test('duplicate question rejected',()=>{const x=structuredClone(q);x.questions[1].id=x.questions[0].id;assert.throws(()=>validateQuiz(x))});
test('invalid correct option rejected',()=>{const x=structuredClone(q);x.questions[0].correctOptionId='absent';assert.throws(()=>validateQuiz(x))});
test('catalog prevents path traversal',()=>{const x=structuredClone(catalog);x.quizzes[0].file='../private.json';assert.throws(()=>validateCatalog(x))});
test('no player-dependent quiz wording',()=>assert.doesNotMatch(JSON.stringify(q),/Norman|Philipp|B1|B2|B3|Beispiel-Liste/));
test('search and no matches',()=>{assert.equal(filterQuizzes(catalog.quizzes,{search:'IMPERIALIS'}).length,1);assert.equal(filterQuizzes(catalog.quizzes,{search:'zzz'}).length,0)});
test('additional faction needs no renderer change',()=>{const extra={...catalog.quizzes[0],id:'another-faction',faction:'Weitere Fraktion',detachment:'Anderes Detachment'};assert.equal(filterQuizzes([...catalog.quizzes,extra],{faction:'Weitere Fraktion'}).length,1)});
test('storage namespace is isolated',()=>{assert.match(storageKey(q),/^pkstratagems:quiz:v1:/);assert.doesNotMatch(storageKey(q),/dropzone:/)});
test('plain text escaped',()=>assert.equal(escapeHTML('<img onerror="test">'), '&lt;img onerror=&quot;test&quot;&gt;'));
