"""User-authorized website revision, 18 September 2026. Does not modify PDFs."""
from pathlib import Path
import json, hashlib
R = Path(__file__).resolve().parents[1]
def load(name): return json.loads((R/name).read_text())
def save(name,value): (R/name).write_text(json.dumps(value,ensure_ascii=False,separators=(',',':'))+'\n')
ref=load('data/reference.json'); ch=load('data/chapters.json'); ms=load('data/missions.json'); cs=load('data/cases.json')
assert ref['meta']['version']=='1.0'
original_words=(R/'data/words.json').read_bytes()
original_scoring={k:{f:v[f] for f in ['name','enemy','scoring','action','line','source']} for k,v in ms.items()}
ref['meta'].update(version='1.1',date='18.09.2026',rulesDate='16.09.2026',rosterDate='18.09.2026',disclaimer='Web-Spielplan v1.1: neue Custodes-Liste vom 18.09.2026, Regel- und Missionsbasis vom 16.09.2026. Beide Captains starten angeschlossen; alle sechs Allarus tragen Guardian Spears. Aufstellungsanker sind keine maßstäblichen Bases. Ganze Einheiten, Reichweiten und Sichtlinien am Tisch prüfen. Regelstichtag 03.10.2026; spätere Änderungen und unbekannte Gegnerlisten sind nicht vorweggenommen. Das ursprüngliche PDF bleibt unverändert auf v1.0.')
ref['revision']={'title':'Neue Formation · Web v1.1','summary':'K1 führt V1, K2 führt V2 – ab Spielbeginn. Zwei angeschlossene Vierer-Bike-Einheiten à 355 Punkte; T1 und T2 jeweils drei Guardian Spears. Philipp räumt missionsrelevante Gegner, Norman übernimmt vorrangig Aktionen und Flächenbesetzung.','tradeoff':'Vier Custodes-Einheiten statt sechs separat agierender Einheiten. Keine Solo-Captains für Viertel oder Aktionen einplanen; kein Vexilla-OC-Bonus bei den Allarus. Ein Nahkampf-Kill erlaubt keine nachträgliche Aktion in der bereits beendeten Schussphase.','formation':'Startanschlüsse: K1 → V1 und K2 → V2. Beide Vierer-Bike-Einheiten auf dem Tisch. S1 im Rhino; B2 (145 P.) und T2 (165 P.) als Reserve-Empfehlung. Damit zehn Aufstellvorgänge im Team. Bei starkem frühen Druck kann T2 ebenfalls starten: dann elf.','rules':'Assemblage of Might gilt für beide Character-Bike-Einheiten gegen das in der eigenen Befehlsphase gewählte Ziel. T1/T2 haben keinen Character und erhalten diesen Bonus nicht. Character-Modell-Effekte werden nicht automatisch auf die drei Vertus übertragen.','source':'L-18 · Philipps Listenänderung 18.09.2026; CU S.35; CR 19.01–19.04. Missionswortlaute unverändert.'}
ref['sources'].append({'id':'L-18','title':'Custodes-Listenstand 18.09.2026','url':'./data/custodes-roster-2026-09-18.txt','note':'Von Philipp vorgegebene Startanschlüsse und Ausrüstung. Nur Website aktualisiert.'})
for u in ref['units']:
 if u['id'] in ['T1','T2']: u.update(wargear='3 × Balistus grenade launcher; 3 × Guardian Spear. Keine Vexilla, keine Misericordia.',formationId=u['id'])
 if u['id'] in ['K1','K2']: u.update(attachedTo='V'+u['id'][1],formationId='V'+u['id'][1]+'/K'+u['id'][1],wargear='Interceptor lance; Salvo launcher.',warlordInRoster=u['id']=='K1')
 if u['id'] in ['V1','V2']: u.update(ledBy='K'+u['id'][1],formationId=u['id']+'/K'+u['id'][1],wargear='3 × Interceptor lance; 3 × Salvo launcher.')
ref['formations']=[dict(u,components=[u['id']]) for u in ref['units'] if u['player']=='Norman' or u['id'] in ['T1','T2']]
for i in [1,2]:ref['formations'].append({'id':f'V{i}/K{i}','components':[f'V{i}',f'K{i}'],'player':'Philipp','name':f'Vertus Praetors {i} + Shield-Captain {i}','models':4,'points':355,'wargear':'4 × Interceptor lance; 4 × Salvo launcher. Ab Spielbeginn eine Attached Unit.'})
ref['deployment']={'custodesRosterEntries':6,'custodesFormations':4,'teamFormations':13,'standardDrops':10,'reserveLimitPerPlayer':500,'reserveNorman':145,'reservePhilipp':165,'bikeFormationPoints':355,'bikePlusAllarusReservePoints':520}
ref['legendNotes']={'1':'B1: Breachers mit Rogue Trader Entourage.','2':'B3 und VO sind getrennte Einheiten.','3':'D1 und S2 sind getrennte Einheiten.','4':'S1 startet im Rhino.','5':'D2: zweite Sperrlinie und Ablösung.','6':'T1: drei Allarus mit drei Guardian Spears, ohne Vexilla.','7':'V1/K1: eine angeschlossene Vierer-Einheit, 355 Punkte.','8':'V2/K2: eine angeschlossene Vierer-Einheit, 355 Punkte.'}
# Resource ordering is unchanged, preserving every existing local checkbox.
ref['resources'][0]='K1 in V1/K1: Sweeping Advance';ref['resources'][1]='K2 in V2/K2: Sweeping Advance'
ref['resources'][4]='V1 in V1/K1: Quicksilver Execution';ref['resources'][5]='V2 in V2/K2: Quicksilver Execution'
def section(i,j,title,text): ch[i]['sections'][j]={'title':title,'text':text}
section(0,3,'Armeen und Warlord','955 + 1.040 = 1.995 Punkte; Detachments und Dispositionen bleiben unverändert. K1 ist im neuen Custodes-Export als Warlord angegeben. Die verbindliche gemeinsame Team-Warlord-Wahl muss mit Normans Liste übereinstimmen; sie wird durch dieses Website-Update nicht zusätzlich unterstellt. Sechs Custodes-Listeneinträge bilden durch K1 → V1 und K2 → V2 vier Einheiten für das Spiel. [L-18; CR 19; E]')
section(0,5,'Web v1.1 · Listenstand und Regelstand getrennt','Die Custodes-Liste und ihre taktischen Folgen wurden am 18.09.2026 aktualisiert. Normans Liste, Missionswortlaute und Eventvorgaben bleiben unverändert. Regelbasis weiterhin 16.09.2026, GW-Regelstichtag 03.10., Listenabgabe 07.10., Veröffentlichung 08.10. Das PDF bleibt absichtlich bei v1.0; für die aktuelle Aufstellung gilt die Website. Empfehlungen sind keine zusätzlichen Regeln. [L-18; E]')
section(1,5,'T1 und T2 · drei Speere / je 165 Punkte','Je drei Allarus, alle mit Balistus grenade launcher und Guardian Spear. Keine Vexilla und keine Misericordia; keinen Vexilla-OC-Bonus einrechnen. T1/T2 bekämpfen Gegner in Aktionsräumen und stützen den Angriff. Sie enthalten keinen Character: kein Assemblage-Bonus. Normans Agenten sollen geräumte Ziele übernehmen; Allarus halten oder handeln selbst, wenn die konkrete Wertung das verlangt. Golden Light für eine tatsächlich benötigte neue Angriffs- oder Missionsroute nutzen. [L-18; CU S.35]')
section(1,6,'V1/K1 und V2/K2 · zwei angeschlossene Einheiten / je 355','K1 führt V1 und K2 führt V2 bereits ab Spielbeginn. Jeweils drei Vertus und ein Captain bilden EINE Vierer-Einheit, mit vier Salvo launchers und vier Interceptor lances. Keine separate Captain-Aufstellung, keine getrennten Viertel- oder Aktionsaufgaben innerhalb einer Einheit. V1/K1 ist der bevorzugte Hauptangriff, V2/K2 schützt dessen Flanke, löst ihn ab oder eröffnet den zweiten Kampf. Alle vier Modelle müssen gemeinsam legal stehen und ihre Bewegung in Kohärenz beenden. [L-18; CR 03,19]')
section(2,1,'2 · Konkrete Standardformation','Beide Captains starten an ihren Vertus. S1 beginnt im Rhino. B2 (145 Punkte) in Normans Reserve, T2 (165) in Philipps Reserve. Combat Landers kann B1, B2 und VO die Option geben, ohne sie alle zu reservieren. Norman hat nach seinen Anschlüssen neun, Philipp vier Formationen: 13 minus S1 im Transport minus B2/T2 in Reserve = zehn Aufstellvorgänge. Eine angeschlossene Bike-Einheit wird zusammen aufgestellt. [L-18; CR 19; IA S.11; E]')
section(2,2,'3 · Reserve sinnvoll variieren','T2 gegen starken frühen Druck bei Gather Intel oder Vital Link zusätzlich aufstellen: dann elf Drops, vier aktive Custodes-Einheiten. Sonst bleibt T2 die flexible 165-Punkte-Verstärkung. Ein angeschlossener Bike-Trupp kostet 355 Punkte; zusammen mit einem Allarus-Trupp wären es 520 und damit mehr als die erlaubten 500 pro Spieler. Keine getrennte Captain-Reserve einplanen. VO zusätzlich in Reserve bedeutet für Norman 195 Punkte und braucht einen Ersatz im Rückraum. Ursprüngliche Reserven rechtzeitig bis Ende SR 3 einsetzen. [L-18; E; CR 20; eigene Empfehlung]')
section(2,3,'4 · Reihenfolge der zehn Drops','B1 früh aufstellen, wenn die Infiltration entscheidend ist oder verdrängt werden könnte. Sonst eindeutige Rückraum-/Rhino-Positionen und Normans Sperren zuerst; T1 dahinter mit Angriffsweg. Die beiden angeschlossenen Bike-Einheiten möglichst zuletzt als je einen Drop aufstellen. Es gibt keine zusätzlichen Captain-Drops zum Verzögern. Anker 7 und 8 sind je ein Raum für vier kohärente Bikes; auf engen Flächen nach hinten staffeln statt die Einheit zu teilen. [L-18; E; eigene Empfehlung]')
section(2,6,'7 · Gemeinsamer Angriffsauftrag','Norman benennt Primärhelfer, Ersatz und Halter. Philipp benennt den Gegner, dessen Entfernung diese Wertung ermöglicht, sowie Angriffs- und Rückzugsweg. Anschließend CP und Aktivierungsreihenfolge abstimmen. Ein Aktionshelfer muss schon in der Schussphase legal stehen und die Aktion beginnen können: Erst im Nahkampf freigeräumtes Gelände erzeugt keine nachträgliche Schussphasen-Aktion. [CR 16; eigene Empfehlung]')
ch[3]['title']='Angeschlossene Captains & CP-Disziplin'
section(3,0,'Startanschluss statt Aufbau-Stratagem','K1 → V1 und K2 → V2 sind fest vorgegeben. Für diese Startanschlüsse werden keine CP für Shoulder the Mantle reserviert; beide Einheiten sind sofort gemeinsam einsatzbereit. Kein planmäßiges Trennen oder Umhängen während des Spiels vorsehen. Shoulder the Mantle bleibt nur eine Option, wenn zu diesem Zeitpunkt wirklich ein nicht führender Captain und ein gültiger, nicht angeschlossener, nicht geschockter Bodyguard-Trupp in 2″ horizontal/5″ vertikal vorhanden sind. Im normalen Startzustand ist das nicht der Fall. [L-18; CU S.35; E]')
section(3,1,'Assemblage-Ziel nach dem gemeinsamen Auftrag wählen','Zu Beginn der eigenen Befehlsphase genau das Feindziel für Assemblage bestimmen, das die angeschlossenen Bike-Einheiten sinnvoll angreifen können und dessen Ausschaltung Missionsraum öffnet. Der Bonus gilt gegen dieses Ziel, nicht pauschal gegen alle Gegner. Keine Runde für einen späteren Anschluss verlieren. Lance und Assemblage sind weiterhin Wurfmodifikatoren mit netto höchstens +1; ein weiterer Bonus kann einen Malus ausgleichen. Nicht beide Einheiten einem unerreichbaren Hauptziel hinterherschicken. [CU S.35; CR 24.21; W-A; eigene Empfehlung]')
section(3,2,'Character-Einheit ist nicht Character-Modell','Assemblage of Might gilt für Modelle in der Character-Einheit: Solange der Captain vorhanden ist, profitieren die Vertus gegen das gewählte Ziel mit. Stirbt der Captain, verlieren die verbleibenden Vertus diesen Bonus laut FAQ. Die Allarus sind nicht Character-Einheiten und erhalten ihn nicht. Emperor’s Auspice und Earning of a Name gelten dagegen für Character-Modelle; daraus keinen Schutz- oder Angriffsbonus für alle drei Vertus ableiten. Auch Slayer of Champions nach seinem exakten Modell-Wortlaut behandeln. [CU S.35; CR 19.03–19.04; W-C]')
section(3,3,'Nach dem Kampf als ganze Einheit weiterdenken','Sweeping Advance bleibt eine begrenzte Ressource; den legalen Endpunkt für die gesamte angeschlossene Einheit vor dem Kampf planen. Ziel: aus der Feuerlinie kommen, den nächsten Gegenangriff drohen oder einen Agenten-Aktionsraum abschirmen. Keine separate Captain-Bewegung für eine zweite Aufgabe buchen. Superhuman Reserves hängt weiterhin an der Warlord-Voraussetzung und am erlaubten CP-Einsatz. [W-K; W-C; CR 15,19; eigene Empfehlung]')
section(3,4,'CP für entscheidende Kämpfe, nicht Startanschlüsse','Philipp priorisiert einen entscheidenden Re-roll, passenden Schutz oder einen konkret wirksamen Kampfeffekt. Norman schützt den Missionshelfer beziehungsweise öffnet mit Nahbereichsfeuer dessen Raum. Strategic Mastery bleibt einmal je Schlachtrunde für die Armee, nicht einmal je Captain. Eine Attached Unit ist auch für das Ein-Stratagem-pro-Einheit-Limit eine Einheit: Captain und Vertus nicht getrennt mit weiteren Stratagems belegen. [CR 15,19; W-K; U S.1]')
section(3,5,'Zwei Angriffswellen statt zwei verlorener Einheiten','V1/K1 räumt den wichtigsten erreichbaren Gegner; V2/K2 bleibt für Flanke, Folgeangriff oder Gegenangriff verfügbar, sofern nicht beide für denselben entscheidenden Kampf nötig sind. Normaler Agentenbeschuss kann einen billigen Screen entfernen, damit 355 Punkte Custodes nicht daran gebunden bleiben. Ein Fight-Stratagem kann in derselben Phase mit Counteroffensive, Epic Challenge oder einem Refresh kollidieren: die gesamte Phase vorher planen. [CR 15; eigene Empfehlung]')
section(4,0,'Auric Champions · sechs Optionen','Shoulder the Mantle (1): situativer Anschluss bei erfüllten Voraussetzungen, kein Aufbauplan für diese Liste. Slayer of Champions (1): nach Eliminierung des markierten Gegners neues Ziel; Modellwirkung beachten. Emperor’s Auspice (1): reaktiver FNP für Characters. Earning of a Name (1): Character-Angriffe gegen Monster/Fahrzeuge verbessern. Vigil Unending (2): noch nicht kämpfender, zerstörter Character schlägt zurück. Superhuman Reserves (2): einmalige Fähigkeit des Custodes-Warlords erneut verfügbar. Character-Modell-Boni nicht den normalen Vertus geben. [CU S.35; W-C]')
section(5,2,'Vier Bikes brauchen einen gemeinsamen Weg','Take to the Skies ignoriert Hindernisse, kostet aber 2″ des jeweiligen Bewegungsmaximums, auch beim Charge. K/V haben hier kein Hover. Für die angeschlossene Vierer-Einheit müssen alle Modelle legal bewegt werden und kohärent enden; ein passender Captain-Endpunkt allein genügt nicht. Fähigkeiten einer Bodyguard-Einheit gelten im Rahmen von CR 19.04 für die Attached Unit, solange ihre Quelle vorhanden ist. Kein getrenntes Turbo- oder Missionsmanöver einplanen. [CR 03,19.04,21; W-K; W-V]')
section(6,1,'Philipp räumt – Norman wertet','Die neue Rollenverteilung ist der Ausgangspunkt: Philipp setzt beide Bike-Einheiten und die Speer-Allarus gegen missionsrelevante Gegner ein. Norman benennt vor jeder Bewegung die handelnden und haltenden Agenten. Töten ist Mittel zum Punktegewinn, nicht Selbstzweck. Wenn nur eine Custodes-Einheit noch die entscheidende Wertung erreichen kann, darf sie die Aufgabe übernehmen; dafür keine sichere Führung einem unnötigen Kill opfern. [L-18; eigene Empfehlung]')
section(7,3,'Worauf bei der Gegnerliste schauen?','Viele kleine Aktionshelfer: ihre wiederholbaren Aktionen stören und die Bike-Einheiten nicht im ersten Screen binden. Wenige robuste Kampfblöcke: passende gemeinsame Angriffskorridore und freie Agenten-Räume prüfen. Vier Custodes-Formationen bedeuten weniger unabhängige Präsenz; keine Auswahl treffen, die in ihrem schlechten Fall mehrere Solo-Captain-Aufgaben voraussetzt. Die unterlegene Paarung muss auch mit Normans verbleibenden Missionshelfern tragfähig sein. [L-18; eigene Empfehlung]')
section(8,0,'Starke Fernkampfarmee','Die vier Modelle jeder angeschlossenen Bike-Einheit vollständig geschützt bereithalten; Captains sind keine vorgeschobenen Einzelköder. B1 nur dort infiltrieren, wo echte Sichtblocker den Plan tragen. Agenten nicht für unwichtigen Beschuss aus Hidden lösen. T2 eröffnet ab SR 2 einen neuen Angriffswinkel, B2 einen Aktionsraum. Nicht beide Bike-Einheiten gleichzeitig in offene Feuerlinien geben. [CR 13; L-18; eigene Empfehlung]')
section(8,2,'Viele Fahrzeuge oder Monster','Die Salvos der angeschlossenen Bike-Einheiten gegen ein geeignetes Assemblage-Ziel bündeln. T1/T2 bringen je drei Speere, aber keinen eigenen Character-Detachment-Bonus. Earning of a Name verbessert nicht die normalen Vertus-Attacken. Norman beseitigt wenn möglich den störenden Screen und führt Missionshelfer nach. Infanteriesperren sind keine unüberwindbaren Mauern für jedes Fahrzeug. [CU S.35; W-C; W-AL; CR 17; L-18]')
section(8,4,'Viele Reserven / Umpositionierungen','Navigator-Modell und 12″-Bereich sichtbar kennzeichnen. VO/B3 sichern erreichbare Lücken. V2/K2 antwortet als ganze angeschlossene Einheit auf eine wertungsrelevante Landung; keinen separaten K2 zurücklassen und V2 gleichzeitig angreifen lassen. T1/T2 können einen anderen Zugang schließen. Kein Bike-plus-Allarus-Reservepaket über der 500-Punkte-Grenze einplanen. [W-NV; CR 03,19,20; E; L-18]')
section(8,5,'Ein besonders starker Hauptblock','Erst prüfen: Muss dieser Block für eure Mission besiegt werden? Falls ja, Assemblage-Ziel zu Befehlsbeginn wählen, die bereits angeschlossenen Bike-Einheiten mit den Speer-Allarus passend koordinieren und Normans Halter beziehungsweise Aktionshelfer mitplanen. Falls nein, Reichweite respektieren, gegnerische Missionshelfer angreifen und andere Räume werten. Keine zusätzliche Extremis-Regel aus eurer Zielbezeichnung ableiten. [CU S.35; L-18; eigene Empfehlung]')
# Mission-specific opening orders replace the obsolete solo-Captain plans.
openings={
'R-TH':[
'Normans Agenten sichern drei Viertel und ein Nicht-Heimziel; die angeschlossenen Bike-Einheiten vernichten die Gegner, die diese Struktur bedrohen. Das vierte Viertel nur mit einer tragfähigen ganzen Einheit ergänzen.',
'VO/B3, D1/S2 oder RH und B1 auf drei verschiedene Viertel außerhalb der 6″-Mittelsperre verteilen. V1/K1 hält einen geschützten Angriffswinkel, V2/K2 den Folgedruck. Beide Captains bleiben Teil ihrer Einheiten. Keine 355-Punkte-Einheit nur für drei zusätzliche Viertelpunkte schutzlos opfern.',
'B1 vor dem Erstzugwurf schützen, Scouts nicht automatisch nach vorn. Nach dem gegnerischen Zug das erreichbare dritte Viertel mit Agenten besetzen. V1/K1 entfernt den Angreifer der Viertelhalter; V2/K2 bleibt mit allen vier Modellen gedeckt und konterbereit.'],
'R-PF':[
'Drei unterschiedliche Nicht-Heimziele nacheinander triangulieren. Norman stellt die Aktionshelfer; die bereits angeschlossenen Bike-Einheiten und die Speer-Allarus öffnen die jeweils nächste Route. Kein Primärzwang für einen riskanten SR-1-Angriff.',
'B1 und D1/S2 erschließen den ersten Aktionsraum, RH/S1 unterstützt. V1/K1 und T1 bedrohen dessen Hauptverteidiger, V2/K2 hält den nächsten Zugang offen. Kein CP oder eigener Zug geht für Startanschlüsse verloren; alle vier Bikes zusammen geschützt aufstellen.',
'Gegnerische Exposition abwarten, B1 und Scouts schützen. Nach seinem Zug einen haltbaren SR-2-Aktionsort bestimmen. V1/K1 räumt dessen Bedrohung, V2/K2 droht der zweiten Route; nicht beide Einheiten für einen irrelevanten Kill abziehen.'],
'R-D':[
'Normans freie Agenten beobachten und löschen erreichbare Decoys. Philipp entfernt die Wächter der schwer erreichbaren Marker. Keine Solo-Captains als zusätzliche Beobachter oder Läufer einplanen.',
'B1 oder S2 bekommt eine tatsächlich sichtbare Beobachtungslinie und verzichtet dafür auf Schießen/Charge. D1 hält den nahen Raum. V1/K1 droht dessen Verteidiger; V2/K2 hält als ganze Einheit einen zweiten Zugang offen. RH oder freie Agenten für spätere Löschkontakte vorsehen.',
'Nach der gegnerischen Markierung den günstigsten legalen Löschweg für RH oder Agenten wählen. V1/K1 räumt die Blockade, statt den Captain allein zum Marker zu schicken. Beobachter vor dem eigenen Schießen benennen; bei der Aktion Sichtbarkeit prüfen.'],
'R-R':[
'Norman soll die ersten sechs Zentralpunkte und anschließend drei unterschiedliche Extraktionen vorbereiten. Beide angeschlossenen Bike-Einheiten bekämpfen die Verteidiger und Gegenangreifer; T1/T2 stützen den Raum ohne Vexilla-OC-Bonus.',
'B1 oder S1/S2 wertet ein erreichbares Zentralziel; der zweite Helfer bleibt geschützt. T1 hält den Angriffsweg offen, V1/K1 droht dem Hauptgegner, V2/K2 deckt die nächste Route. Gegen hohen frühen Druck T2 bereits aufstellen. Zielkontrolle mit den tatsächlich anwesenden Modellen berechnen, nicht mit dem alten Vexilla-Bonus.',
'Das weniger belastete Zentralziel angreifen, nicht beide Bike-Einheiten blind in dieselbe Mitte schicken. Agenten übernehmen die Kontrolle nach einem gezielten Kampf. Wenn die ersten sechs Punkte nur durch den Verlust beider Angriffsverbände erreichbar wären, stattdessen spätere Extraktionswege sichern.'],
'R-P':[
'Norman hält Zentrum und ein weiteres Nicht-Heimziel und besetzt wichtige eigene Geländegebiete. Philipp räumt deren Angreifer mit zwei angeschlossenen Bike-Einheiten; eine bleibt als Antwort auf Vanguard-Eindringlinge beweglich.',
'B1/S1 strebt die Mitte an, D1 die Expansion. B3/VO sichern relevante Heimatflächen. V1/K1 deckt den Zentralzugang, V2/K2 steht als vollständige Einheit auf der wichtigsten Einbruchroute. T1 bekämpft Gegner an der zweiten Fläche; die Allarus ersetzen nicht automatisch den Agentenhalter.',
'Vanguard-Kandidaten und freie eigene Geländegebiete identifizieren. Nach dem gegnerischen Zug einen Raum gemeinsam zurücknehmen und mit Agenten besetzen. Ein separat losgeschickter Captain ist keine Option; wenn das Zentrum zu teuer ist, erst die Expansion stabilisieren.'],
'P-TH':[
'Norman richtet eine wiederholbare sichere Aktionsfläche ein. Philipp entfernt die Gegner, die Heimziel + Expansion + ein Zentralziel bedrohen, und hält den zweiten Bike-Verband für den Folgekampf bereit.',
'B1/S1 führt die erste sichere Asset-Aktion aus, D1/S2 stützt die Kontrolle. V1/K1 hält die Angriffsroute offen, T1 unterstützt mit drei Speeren. V2/K2 bedroht die zweite Front als angeschlossene Einheit; keine separate Captain-Aktion einplanen.',
'Nach der gegnerischen Verteilung den haltbaren Nicht-Heimraum wählen. Agenten starten dort die Aktion, sofern sie schon in der Schussphase berechtigt sind. Philipp entfernt den Gegner, der den Abschluss oder die nächste Haltewertung verhindert; eine schon beendete Schussphase lässt sich nicht nach dem Nahkampf nachholen.'],
'P-PF':[
'Ein haltbares Zentralziel ist der Schwerpunkt. Norman stapelt dort die Operationsmarker; V1/K1 und die Speer-Allarus beseitigen den zentralen Druck, V2/K2 bleibt die zweite Angriffswelle.',
'B1/S1 kontrolliert das bevorzugte Zentralziel und startet Maintain Control. T1 und V1/K1 schützen den Raum durch Gegenangriffsdrohung. Bei starkem frühen Druck T2 auf dem Tisch. Allarus-Kontrolle ohne Vexilla-Bonus berechnen; V2/K2 nicht für eine zweite ungeschützte Mitte verschwenden.',
'Nach dem gegnerischen Vorstoß einen einzigen haltbaren Zentralraum gemeinsam erkämpfen. Norman hält einen aktionsfähigen Helfer und D2 als Ablösung bereit. Beide Bike-Einheiten beginnen bereits angeschlossen; keine Subductor-Welle ohne anschließenden Custodes-Gegenangriff opfern.'],
'P-D':[
'Norman sichert Zentralzugang und Sweep-Helfer; Philipp bekämpft die Blockaden und hält eine angeschlossene Bike-Einheit für den wahrscheinlichen letzten Markerraum bereit. Zwei erreichbare Endorte verfolgen, weil beide Teams Marker entfernen können.',
'B1/S1 startet den ersten Sweep nur bei tragfähiger Kontrolle. V1/K1 und T1 decken die Mitte. V2/K2 steht als ganze Vierer-Einheit zwischen zwei möglichen Endorten; ein Agentenhalter muss ihr folgen können. Nicht nur einen Captain als spätere Eskorte kalkulieren.',
'Nach gegnerischer Markerauswahl und Sweep den Endortplan anpassen. Normans Helfer an der Mitte schützen, V2/K2 mit gemeinsamem Weg zum wahrscheinlichen letzten Geländegebiet bereitstellen. Speer-Allarus können den zweiten Zugang bekämpfen.'],
'P-R':[
'Normans B1/B2 oder VO arbeiten in einer leeren gegnerischen Territoriumsfläche. Die angeschlossenen Bike-Einheiten und Speer-Allarus öffnen und schützen den Zugang. Ein sicherer SR-1-Abschluss wird nicht vorausgesetzt.',
'B1 nur dann vorziehen, wenn nach normaler Bewegung eine legale, geschützte Operation in einer leeren gegnerischen Geländegrundfläche möglich ist. V1/K1 deckt die Route, V2/K2 die offene Flanke. Keine ungeschützte 355-Punkte-Einheit zum Primärhelfer machen, solange Agenten handeln können.',
'Gegnerischen Vorstoß abwarten und frei werdende Geländegebiete suchen. B1 zunächst schützen, B2-Landung vorbereiten. V1/K1 greift den Wächter der geplanten Operationsfläche an; V2/K2 schützt den Verbindungskorridor. Captains bleiben angeschlossen.'],
'P-P':[
'Zwei unterschiedliche Aktionsorte mit Normans Agenten aufbauen. Die angeschlossenen Bike-Einheiten und Speer-Allarus räumen gegnerische Halter und schützen die Helfer. Keine zusätzlichen Captain-Aktionen oder Vexilla-OC einrechnen.',
'B1/S1 startet die erste Sabotage, D1/S2 bereitet den zweiten Ort vor. V1/K1 räumt den relevanten Verteidiger, V2/K2 hält den Gegenangriff bereit. Aktionshelfer muss schon vor dem Nahkampf in der Schussphase legal handeln können.',
'Eine sichere eigene Aktion priorisieren und den schwächeren gegnerischen Aktionsraum angreifen. Agenten bestreiten die Kontrolle; ein angeschlossener Bike-Trupp beseitigt den wichtigen Helfer oder seine Eskorte. Nicht beide 355-Punkte-Einheiten gleichzeitig für kleine Nebenaufgaben binden.']}
ph={
'R-TH':[
'V1/K1 bleibt als angeschlossene Einheit gedeckt mit Angriffswinkel auf die Viertelbedrohung. V2/K2 sichert den Folgeangriff. Salvos auf missionsrelevante Ziele richten; keine einzelne Captain-Viertelaufgabe.',
'T2 bringt drei Speere auf eine haltbare Flanke. V1/K1 räumt den Gegner, der die nächste Viertelwertung verhindert; Agenten übernehmen den freigekämpften Raum.',
'Den gemeinsamen Angriff mit V1/K1 ausführen, V2/K2 konterbereit halten. Beide Verbände sind längst angeschlossen; zusätzliche Viertel mit Normans freien Einheiten abdecken.',
'Gegnerische Angreifer auf Viertelhalter ausschalten. Golden Light oder Sweeping Advance nur sparen, wenn heute kein entscheidender Einsatz nötig ist; Endpunkte für die ganze Einheit planen.',
'Kampf und Bewegung auf tatsächlich fehlende Viertel, Kills oder Nicht-Heimkontrolle ausrichten. Ein Bike-Verband zählt einschließlich Captain nur als eine Einheit. Keine eigene Führung für einen unnötigen Kill riskieren.'],
'R-PF':[
'V1/K1 und T1 bedrohen den ersten Aktionsraum; V2/K2 bleibt für den nächsten offen. T2 kann Reserve bleiben, wenn Normans erste Linie tragfähig ist.',
'V1/K1 entfernt die Gefahr für Ziel 1. T2 unterstützt mit drei Speeren die zweite Route. Den Aktionshelfer nicht erst nach der Schussphase in den Raum erwarten.',
'Den ersten Angriffsverband ablösen und V2/K2 gegen den Wächter von Ziel 2 oder der dritten Route richten. Captain und Vertus bleiben jeweils zusammen.',
'Die dritte Markierung durch gezieltes Freiräumen absichern. Allarus und Bike-Trupp nicht für einen entfernten Großgegner vom Aktionskorridor abziehen.',
'Bei erreichbarem Primärdeckel gegnerische Wertung und Sekundäraufgaben priorisieren. Vier Endziele nur anstreben, wenn ihr den Bonus noch benötigt; nötigenfalls übernimmt die ganze Custodes-Einheit ein Ziel.'],
'R-D':[
'V1/K1 deckt Normans Beobachter. V2/K2 bedroht den zweiten Markerweg als ganze Einheit. Keine vier Bikes für eine Beobachtungsaktion stilllegen, solange ein Agent verfügbar ist.',
'Blockierende Gegner mit V1/K1 oder den Speer-Allarus ausschalten. V2/K2 übernimmt einen gefährlichen Löschlauf nur als ganze Einheit und nur für einen wertungsrelevanten Gewinn.',
'Ein wichtiges Markergebiet öffnen und Normans Löschhelfer nachführen. Mindestens eine Bike-Einheit für die nächste gegnerische Markierung beweglich halten; keinen Captain separat zurücklassen.',
'Golden Light kann einen neuen Zugang erschließen. T1/T2 bekämpfen dort den Wächter; ein eigener Helfer muss für den nötigen Löschkontakt rechtzeitig nachkommen.',
'Gegnerischen Decoy-Endbonus unterbrechen, statt irrelevante Kills zu sammeln. Fehlt ein Agent, darf eine ganze Custodes-Einheit selbst den entscheidenden Löschkontakt herstellen.'],
'R-R':[
'T1 bekämpft den Druck auf den Zentralhelfer; V1/K1 steht für den Hauptgegenangriff, V2/K2 schützt die zweite Route. T2 bei hohem frühen Druck auf dem Tisch. Keine Vexilla-OC einrechnen.',
'T2 als Speer-Verstärkung für ein neues Ziel einsetzen. V1/K1 beseitigt den Verteidiger, der Normans erste Extraktion gefährdet. Agenten handeln, Custodes kämpfen, soweit die konkrete Wertung es zulässt.',
'V1/K1 schafft den Übergang zum zweiten Ziel; V2/K2 bleibt die zweite Angriffswelle. Einen anderen Agenten als Helfer nachführen, nicht den Captain aus der Einheit lösen.',
'Die dritte Extraktion durch Ausschalten des relevanten Gegners sichern. Allarus halten bei Bedarf selbst, aber ein geräumtes Ziel rechtzeitig an Normans Helfer übergeben.',
'Bei voller eigener Primärwertung den letzten gegnerischen Extraktionsraum angreifen. Falls eigene Punkte fehlen, kann eine ganze Custodes-Einheit handeln; nicht starr am Kill-Auftrag festhalten.'],
'R-P':[
'V1/K1 kontrolliert mit Gegenangriffsdrohung den Zentralzugang; V2/K2 bleibt auf der wichtigsten Vanguard-Einbruchroute. T1 bekämpft Gegner nahe der Expansion.',
'T2 am zweiten Wertungsraum einsetzen. Den Gegner priorisieren, dessen Entfernung die nächste Haltewertung sichert; B2 oder ein anderer Agent übernimmt die Fläche.',
'Ein gebündelter Angriff stabilisiert die Zwei-Ziele-Struktur. Eindringlinge mit V2/K2 oder einem Allarus-Trupp beantworten, nicht mit einem künstlich abgetrennten Captain.',
'Wertungsrelevante Eindringlinge aus dem eigenen Territorium räumen. Allarus ohne Ersatz nicht vom letzten Halteort abziehen; eine ganze Bike-Einheit kann den Gegenangriff übernehmen.',
'Zentral- und Nicht-Heimwertung vor zusätzlichen Kills sichern. Den Endbonus nur verfolgen, wenn erreichbar und noch nötig; Halter für den letzten gegnerischen Zug erhalten.'],
'P-TH':[
'V1/K1 hält den Gegenangriff auf Normans Asset-Fläche offen. T1 bedroht die Verteidiger mit drei Speeren; V2/K2 deckt die zweite Front.',
'T2 hilft, das dritte Ziel zu räumen. Agenten übernehmen die Kontrolle. V2/K2 nur dann exponieren, wenn ein echter Gegner oder eine nötige Wertung das rechtfertigt.',
'Mit der bereits angeschlossenen V1/K1-Einheit den gegnerischen Halter des vierten Ziels angreifen oder bestreiten. V2/K2 schützt die eigene Drei-Ziele-Struktur.',
'Gegnerisches Mehr-Ziele-Werten gezielt verhindern. Beide Bike-Einheiten nicht gleichzeitig ohne Rückweg aus der Reichweite von Normans Haltern bewegen.',
'Nur noch den Kampf führen, der fehlende eigene Punkte ermöglicht oder gegnerische Wertung verhindert. Notfalls selbst als ganze Einheit halten; kein isolierter Captain-Vorstoß.'],
'P-PF':[
'T1 stützt Normans Aktionshalter, V1/K1 steht für den Hauptgegenangriff. T2 bei zentraler Überlastung direkt aufstellen. V2/K2 bleibt als vollständige Einheit in zweiter Welle.',
'V1/K1 vernichtet den wertungsrelevanten Zentralangreifer. T1/T2 helfen mit drei Speeren, aber ohne Assemblage-Bonus. Nicht vom Link-Raum einer entfernten Feuerplattform nachjagen.',
'Angeschlagene erste Welle ablösen, V2/K2 gegen den nächsten Hauptgegner einsetzen. Genug Präsenz für die Kontrolle des markierten Zentralziels erhalten.',
'Führung durch Schutz von Normans Markerraum sichern. Golden Light erst einsetzen, wenn die aufgegebene Fläche ersetzt ist; nicht für einen optionalen Kill die Link-Wertung aufbrechen.',
'Zentralziel notfalls als ganze Custodes-Einheit zurückholen. Den gegnerischen Heimziel-Bonus nur anstreben, wenn noch benötigt; sonst gegnerische Halter und Aktionshelfer bekämpfen.'],
'P-D':[
'V1/K1 und T1 stützen den zentralen Sweep-Raum. V2/K2 steht zwischen zwei möglichen letzten Markerflächen; für vier Bikes einen legalen gemeinsamen Weg offenhalten.',
'T2 auf den Zugang zum wahrscheinlichen Endort bringen. V2/K2 früh in Angriffsreichweite bereitstellen; nicht erst nach der zweiten gegnerischen Alleinwertung reagieren.',
'Die letzte Geländegrundfläche mit einer angeschlossenen Bike-Einheit und gegebenenfalls Allarus räumen. Normans Besetzer muss rechtzeitig nachkommen; ein einzelner Kill entfernt nicht automatisch alle Mitbewohner.',
'Eine vollständige Gegenangriffseinheit nahe der Endfläche halten. Bei ungünstigem Kampf genügt zunächst eigene Präsenz, um gegnerische Alleinwertung zu verhindern; nicht alle Kräfte auf einen Zugang drängen.',
'Eigene End-of-Turn-Wertung und Spielendbonus getrennt planen. Für Erstspieler muss der verbleibende Halter den letzten Gegnerzug überstehen; Angriff nur für noch benötigte Punkte oder Denial.'],
'P-R':[
'V1/K1 schützt die Operationsroute; V2/K2 verhindert den gegnerischen Zentraldurchmarsch. Kein Captain allein als zusätzlicher Helfer, beide Vierer-Einheiten bleiben einsatzfähig.',
'T2 bekämpft den Wächter eines Nachbargebiets. V1/K1 öffnet den Weg für B2; V2/K2 sichert den Verbindungskorridor. Allarus handeln nur selbst, wenn kein geeigneter Agent die nötige Operation schafft.',
'Den störenden Gegner im Arbeitsraum gezielt entfernen. Sweeping Advance für den gemeinsamen Endpunkt der Bike-Einheit planen, nicht für getrennte Captain-Missionsarbeit.',
'Einen wertungsrelevanten Angriff auf den nächsten Störer oder die Heimzielroute vorbereiten. Den laufenden Agenten-Aktionsraum nicht für einen optionalen Endbonus ungeschützt lassen.',
'Entscheiden zwischen benötigtem Heimzielbonus, Operationshilfe und gegnerischem Denial. Eine ganze Custodes-Einheit darf die entscheidende Missionsaufgabe übernehmen, wenn kein Agent sie mehr erfüllen kann.'],
'P-P':[
'T1 bedroht die Verteidiger des ersten Aktionsorts. V1/K1 und V2/K2 decken unterschiedliche Annäherungen; eine bleibt Gegenangriff, statt beide früh ohne Helfer zu binden.',
'T2 bekämpft einen gefährlichen Halter. Beide angeschlossenen Bike-Einheiten öffnen Normans zweite Aktionsfläche oder entfernen gegnerische Missionshelfer; keine separate Captain-Aktion zählen.',
'Einen Angriff nur dort binden, wo ein berechtigter Helfer rechtzeitig die Kontrolle in Punkte umsetzen kann. Allarus-Speere nutzen, aber ohne Vexilla-OC und ohne Character-Detachment-Bonus rechnen.',
'Den zweiten gegnerischen Aktionsort angreifen und eine eigene Gegenangriffseinheit ungebunden erhalten. Normans zwei Helfer nicht für einen beliebigen Kill opfern.',
'Bei vollen eigenen Primärpunkten gegnerische Abschlüsse verhindern. Fehlen eigene Punkte und Agenten, kann eine ganze Custodes-Einheit selbst sabotieren; die Siegpunktentscheidung geht vor dem Kill-Auftrag.']}
for k,m in ms.items():
 for name,text in zip(['opening','first','second'],openings[k]):m[name]=text
 for row,text in zip(m['rounds'],ph[k]):row['philipp']=text
 m['rosterVersion']='1.1';m['revisionSource']='L-18 · angepasste Taktik zur Startformation; Wertung und Missionswortlaut unverändert.'
ms['R-TH']['fail']='Fällt B1 früh, übernehmen RH/S2 oder ab SR 2 B2 die Viertelaufgabe. Ein Bike-Trupp kann nur als ganze Einheit einspringen und zählt mit Captain nicht als zwei Viertelhalter. Erst drei Viertel und ein Nicht-Heimziel sichern, nicht beide Angriffsverbände für ein unsicheres viertes streuen.'
ms['R-R']['rounds'][1]['norman']='Erste Extraktion durch B1/S1. B2 landet zur Unterstützung eines frischen Aktionsziels. Zwei parallele Aktionen nur bei haltbaren Zielen; bei 4 Haltepunkten werden 18 Rohpunkte auf 15 begrenzt.'
ms['P-R']['rounds'][4]['norman']='Letzte Operation plus Nicht-Heimwertung am Zugende. B1/B2 oder ein anderer Agent übernimmt die Aufgabe; falls keiner mehr verfügbar ist, früh mit Philipp über eine Custodes-Einheit als Ersatz entscheiden.'
layout_types={'A01':'step','A02':'horizontal','A03':'step','A04':'sidestep','A05':'diagonal','B01':'horizontal','B02':'quarters','B03':'step','B04':'step','B05':'diagonal','C01':'quarters','C02':'diagonal','C03':'quarters','C04':'step','C05':'sidestep','C06':'vertical','C07':'horizontal','C08':'quarters','C09':'sidestep','C10':'step'}
notes={
'step':'Die gestuften Zonen als zwei geschützte Angriffskorridore nutzen. Anker 7/8 jeweils für die ganze Vierer-Einheit; Agenten an die vorderen Wertungsflächen, Allarus dahinter mit freiem Weg. Bei Platzmangel nach hinten staffeln, nicht Captain und Vertus trennen.',
'horizontal':'Beide Vierer-Bike-Einheiten hinter den vorderen Agenten staffeln. Einen zentralen Ausfallweg je Einheit freihalten; ein Verband greift an, der andere hält Folge- oder Gegenangriff offen. T1 nutzt seinen Speertrupp für den umkämpften Zugang.',
'sidestep':'Die breite Zone für einen vollständigen Vierer-Bike-Verband nutzen und die zweite Einheit nicht quer über mehrere getrennte Aufgaben verteilen. Agenten bedienen Expansion und Aktionsraum; Allarus bekämpfen deren Verteidiger.',
'diagonal':'Entlang der Diagonale einen gemeinsamen Angriffsweg pro Vierer-Bike-Einheit offenhalten. Vorderer Agentenhalter und dahinterstehende Custodes nicht gegenseitig blockieren. Territorial- und Aufstellungsgrenze bleiben unterschiedliche Linien.',
'quarters':'Den inneren Eckzugang nicht mit beiden Vierer-Bike-Einheiten zustellen. Erste Angriffseinheit und zweite Welle staffeln, daneben Platz für Normans Helfer. Kein isolierter Captain an der inneren Ecke und kein Vexilla-Bonus am Allarus-Anker.',
'vertical':'Von der seitlichen Zone aus zwei gemeinsame Wege für die Vierer-Bike-Einheiten vorsehen. Agenten stehen an den vorgesehenen Aktionsorten, Allarus bekämpfen den näheren Verteidiger. Anker 7/8 nicht als je zwei unabhängige Drops lesen.'}
for c in cs:
 c['formation_note']=notes[layout_types[c['code']]];c['rosterVersion']='1.1'
 if c['code']=='C03':c['role_note']='Normans freie Agenten und RH für Löschkontakte einplanen; V2/K2 als ganze angeschlossene Einheit gegen die Blockade bereithalten. B1 nicht ohne Rückweg an der ausgeschnittenen Mitte platzieren.'
assert original_words==(R/'data/words.json').read_bytes()
assert original_scoring=={k:{f:v[f] for f in ['name','enemy','scoring','action','line','source']} for k,v in ms.items()}
for name,data in [('reference',ref),('chapters',ch),('missions',ms),('cases',cs)]:save('data/'+name+'.json',data)
print('Updated 20 scenarios, all 50 Philipp round assignments, roster and formation chapters. Mission scoring and words unchanged.')
